### ISSUE TITLE
this is absolutely USELESS

### ISSUE THREAD

**Issue by Drixxytec** [MarvelcoOGFN/Battlepass-Ids#1]
erm in backends u can put anything the game doesnt care like
you can put "skibidisigmabattlepassseason1realfreevbucks" and it would work probably
😨😨

**Comment by MarvelcoOGFN** [comment]
> erm in backends u can put anything the game doesnt care like you can put "skibidisigmabattlepassseason1realfreevbucks" and it would work probably 😨😨

what is bro even saying ofc not wtf it wont work like that are you a retard?

**Comment by Drixxytec** [comment]
ask pommes 🙏💀

**Comment by Drixxytec** [comment]
> > erm in backends u can put anything the game doesnt care like you can put "skibidisigmabattlepassseason1realfreevbucks" and it would work probably 😨😨
> 
> what is bro even saying ofc not wtf it wont work like that are you a retard?

Also yeah it will work the game doesn't care if the offerID is correct or not 🙏

**Comment by Drixxytec** [comment]
try it

**Comment by MarvelcoOGFN** [comment]
> > > erm in backends u can put anything the game doesnt care like you can put "skibidisigmabattlepassseason1realfreevbucks" and it would work probably 😨😨
> > 
> > 
> > what is bro even saying ofc not wtf it wont work like that are you a retard?
> 
> Also yeah it will work the game doesn't care if the offerID is correct or not 🙏

bro isnt cooking 💀 litterly it wont this proves your a skidder

**Comment by MarvelcoOGFN** [comment]
> try it

try it your self bro

**Comment by Drixxytec** [comment]
> > try it
> 
> try it your self bro

i did and it worked 🙏
